package Projects;

//  <<<<<<<<<<<<<<<<     TASK 1 - NUMBER GAME    >>>>>>>>>>>>>>>>>
// 1. Generate a random number within a specified range, such as 1 to 100.
// 2. Prompt the user to enter their guess for the generated number.
// 3. Compare the user's guess with the generated number and provide feedback on whether the guessis correct, too high, or too low.
// 4. Repeat steps 2 and 3 until the user guesses the correct number.
// You can incorporate additional details as follows:
// 5. Limit the number of attempts the user has to guess the number.
// 6. Add the option for multiple rounds, allowing the user to play again.
// 7. Display the user's score, which can be based on the number of attempts taken or rounds won.

import java.util.Random;
import java.util.Scanner;
public class NumberGuessingGame{
    // Declaring rules
    public static void rules(){
        System.out.println("|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||");
        System.err.println("|                                           WELCOME TO THE GAME                                                       |");
        System.out.println("|Description -> (1)You have to guess a number that is generated by the computer repeadately until it match.           |");
        System.out.println("|               (2)If you guessed correct number in less than or equal to 10 attempts ,You will won otherwise you loss|");
        System.out.println("|               (3)You can play it multiple times . You have to enter 1 when you have asked to play again or not      |");
        System.out.println("|               (4)At end when you stop playing , Total game played , won , loss data will be displayed.              |");
        System.out.println("|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||");
    }
    public static void main(String[] args) {
        rules();
        System.out.println("________________________________________________________");
        // generating a random number
        Random rand = new Random();
        int random = rand.nextInt(100);

        Scanner sc = new Scanner(System.in);
        int num = -1;
        int ch = 0;
        int total_time_played = 1; // this is to store that how many times you played the game
        int won = 0;  // this is to store that how many times you won the game.
        while (true) {
            int attempts = 1 ;
            while (true) {
                while (true) {
                    System.out.println("..............................................");
                    System.out.print(attempts+") Guess a number ( 1 - 100 ) => ");
                    try {
                        num = sc.nextInt(); // guessed number by user
                        ch = 1;
                    }
                    catch(Exception e){
                        sc.next();
                    }
                    if (ch == 1 && num >= 0 && num <= 100) {
                        break;
                    }
                    else{
                        System.out.println("----------------------------------------");
                        System.out.println(" INVALID NUMBER or OUT OF RANGE(1-100)  ");
                        System.out.println("----------------------------------------");
                    }

                }
                if ( num == random){
                    System.out.println("_______________________________________________");
                    if (attempts <= 10) {
                        won += 1;
                        System.out.println("                < YOU WON >                    ");
                    }
                    else{
                        System.out.println("                < YOU LOSS >                    ");
                    }
                    System.out.println("You guessed the correct number ("+random+") in "+attempts+" attempts.");
                    System.out.println("_______________________________________________");
                    break;
                }
                else if (num < random  && num >= 0 ) {
                    System.out.println("   ALERT - Guessed number is 'TO LOW' !Try Again!");
                }
                else if (num > random && num <= 100) {
                    System.out.println("   ALERT - Guessed number is 'TO HIGH' !Try Again!");
                }
                attempts += 1 ;
            }
            System.out.print("WANT TO PLAY AGAIN (Enter 1) otherwise enter any number => ");
            int a = -1;
            try {
                a = sc.nextInt();
            } catch (Exception e) {
                sc.next();
            }
            if (a != 1) {
                // FINAL RESULT
                System.out.println("<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>");
                System.out.println("You played "+total_time_played+" times this game.");
                System.out.println("You Won "+won+" times this game.");
                System.out.println("You Loss "+( total_time_played - won )+" times this game.");
                System.out.println("<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>");
                break;
            }
            total_time_played += 1;
        }
        System.out.println("_______________________________________________");
    }
}
